const ROLES = {
  ADMIN: 'ADMIN',
  LIBRARIAN: 'LIBRARIAN',
  MEMBER: 'MEMBER'
};

// Define the Rules
const PERMISSIONS = {
  // Queries
  getAuthorById: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getAllAuthors: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  searchAuthorsByName: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getBookById: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getAllBooks: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getTotalBooksCount: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  searchBooksByTitle: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  searchBooksByAuthorName: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  searchBooksWithStats: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getBooksByAuthorId: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getBookCopyById: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getAllBookCopiesByBookId: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getAvailableBookCopiesByBookId: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getAllBookCopies: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getTotalBookCopiesCount: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getBookDataByBookCopyId: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  getAllNewBookRequests: [ROLES.ADMIN, ROLES.LIBRARIAN],
  getAllNewBookRequestsByStatus: [ROLES.ADMIN, ROLES.LIBRARIAN],

  // Mutations
  createAuthor: [ROLES.ADMIN, ROLES.LIBRARIAN],
  updateAuthor: [ROLES.ADMIN, ROLES.LIBRARIAN],
  deleteAuthor: [ROLES.ADMIN, ROLES.LIBRARIAN],
  createBook: [ROLES.ADMIN, ROLES.LIBRARIAN],
  updateBook: [ROLES.ADMIN, ROLES.LIBRARIAN],
  deleteBook: [ROLES.ADMIN, ROLES.LIBRARIAN],
  createBookCopy: [ROLES.ADMIN, ROLES.LIBRARIAN],
  createBookCopies: [ROLES.ADMIN, ROLES.LIBRARIAN],
  deleteBookCopy: [ROLES.ADMIN, ROLES.LIBRARIAN],
  markCopyAsAvailable: [ROLES.ADMIN, ROLES.LIBRARIAN],
  markCopyAsUnavailable: [ROLES.ADMIN, ROLES.LIBRARIAN],
  markCopyAsDamaged: [ROLES.ADMIN, ROLES.LIBRARIAN],
  createNewBookRequest: [ROLES.ADMIN, ROLES.LIBRARIAN, ROLES.MEMBER],
  updateNewBookRequestStatus: [ROLES.ADMIN, ROLES.LIBRARIAN]
};

module.exports = { PERMISSIONS, ROLES };